### ISSUE TITLE
tWonder stability

### ISSUE THREAD

**Issue by anwaldt** [anwaldt/seamless#3]
After 2 days, tWonder 1-4 were not active on WFS node 2:

Jun 30 11:03:36 3900-zg-re-03 start-twonder.sh[896]: Cannot connect to cwonder...
Jun 30 11:03:37 3900-zg-re-03 start-twonder.sh[983]: Cannot connect to cwonder...
Jun 30 11:03:38 3900-zg-re-03 start-twonder.sh[989]: Cannot connect to cwonder...
Jun 30 11:03:39 3900-zg-re-03 start-twonder.sh[992]: Cannot connect to cwonder...

**Comment by ntonnaett** [comment]
https://github.com/ntonnaett/wonder-lite/issues/9

**Comment by ntonnaett** [comment]
Running twonders work after cwonder restart. Dead twonders might not be deleted from cwonder's list.
