### ISSUE TITLE
twonder stopped running

### ISSUE THREAD

**Issue by anwaldt** [anwaldt/seamless#31]
- on both WFS machines, twonder 1-4 were not working

- restarting the twonder services solved the problem

**Comment by ntonnaett** [comment]
Maybe related to RemoveIPC in systemd. But that would be weird because it only has problems with the first four clients...

**Comment by ntonnaett** [comment]
Set RemoveIPC=no on rendering machines. If this doesn't help, maybe a jack update helps.
